# Site
repository: hoyo1744/hoyo1744.github.io
#favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: 엄호용
title: Backend Developer
email: hoyo1744@gmail.com
website: https://velog.io/@hoyo1744

# Dark Mode (true/false/never)
dark_mode: false

# Social links
github_username: hoyo1744


# Additional icon links
additional_links:
- title: velog
  icon: fas fa-globe
  url: https://velog.io/@hoyo1744/posts

# About Section
about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  3년차 백엔드 개발자로 **엔드포인트 플랫폼**을 개발했습니다.  
  대규모 트래픽 환경에서도 안정적으로 운영될 수 있는 시스템을 만들기 위해 **서비스 안정화** 및 **성능 개선**에 주력하고 있습니다.  

  개발 과정에서 원칙을 지키되 실용적인 방식을 선택하며, 팀원들과의 기술 토론을 통해 **유지보수성과 성능을 모두 고려한 해결책**을 찾습니다.  
  학습한 내용과 문제 해결 경험은 블로그에 기록하여 **개인의 성장 → 조직의 성장**으로 확장시키는 것을 목표로 합니다.

  

content:

  - title: Experience 
    layout: list 
    content:
      - layout: left
        title: 안랩
        sub_title: 엔드포인트 플랫폼 개발
        quote: >
          엔드포인트 플랫폼 전반적인 시스템 개발 및 성능 개선
        description: | 
          - 인덱스, 쿼리 튜닝, 시스템 설정 최적화를 통한 성능 개선
          - API 게이트웨이 도입으로 트래픽 처리 향상
          - Kafka Producer 병목 해소
          - 레거시 배치 서비스 개선으로 서비스 안정화
          - 테스트 환경 및 **BVT(Build Verification Test)** 자동화 구축으로 인력 효율화

  - title: Project # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 게이트웨이 도입
        sub_title: 엔드포인트 플랫폼
        quote: >
          BFF 서비스로서 인증 통합 및 캐싱 적용으로 서비스 트래픽 처리율 개선
        description: | # this will include new lines to allow paragraphs
          - **문제** : 최대 동시 연결 클라이언트가 12만대로 제한되어 성능 개선 필요  
          - **원인** : 인증/인가 및 Read/Write 트래픽이 Blocking 작업으로 인한 자원 고갈  
          - **해결**  
            - 여러 서비스에서 중복으로 검증하던 인증 로직 통합  
            - Read(캐싱) / Write 트래픽 분리로 처리율 향상  
            - Write 서비스의 Tomcat 스레드 수 및 Connection Pool 최적화  
          - **성과**  
            - 인증/인가 로직 통합으로 유지보수 효율화  
            - Read 병목 제거 및 Write TPS **30%** 개선
      - layout: left
        title: Kafka Producer 개선
        sub_title: 앤드포인트 플랫폼
        quote: >
          Kafka 배치 전송 및 DLQ 도입으로 대용량 트래픽 환경에서 메시지 처리량 개선
        description: | # this will include new lines to allow paragraphs
          - **문제** : 대용량 트래픽 환경에서 메시지 비동기 처리 지연
          - **원인** : Producer가 메시지를 단건 전송
          - **해결**
            - Kafka Producer 배치 전송 설정
            - DLQ(Dead Letter Queue) 도입: 전송 실패 메시지를 별도 토픽에 보관
          - **성과**
            - DLQ 유실 방지 및 TPS 30% 개선
      - layout: left
        title: 레거시 배치 서비스 개선
        sub_title: 엔드포인트 플랫폼
        quote: >
          Spring Batch 적용으로 서비스 안정화
        description: | # this will include new lines to allow paragraphs
          - **문제** : 자바 기본 스레드로 구현되어 Exception에 취약해 서비스 중지 재현
          - **원인**
            - Exception 핸들링 미흡
            - 잘못된 데이터 포맷에 대한 Skip, retry 정책 미흡
          - **해결**
            - Spring Batch를 적용시켜 Exception, skip, retry 정책 고도화
            - DLQ(Dead Letter Queue) 도입: 전송 실패 메시지를 별도 토픽에 보관
          - **성과**
            - 배치 서비스 이슈 발생 건 수 **50% 이상 감소**
      - layout: left
        title: 테스트 자동화
        sub_title: 엔드포인트 플랫폼
        quote: > 
          BVT 자동화로 휴먼 에러 최소화
        description: | # this will include new lines to allow paragraphs
          - ELK 스택으로 클라이언트 BVT 자동화 환경 구축 및 테스트 실패시 사내 메신저 알림 연동
          - 팀 내 테스트 작성 추진 및 테스트 2000건 이상 작성
      - layout: left
        title: 서비스 안정화
        sub_title: 엔드포인트 플랫폼
        quote: >
          인덱스 및 쿼리 튜닝으로 사용자 경험 개선
        description: | # this will include new lines to allow paragraphs
          - postgres에서 ShareLock과 Row ExclusiveLock의 충돌로 deadLock 발생으로 인한 CPU 과점유 문제 개선 ([분석문서](https://velog.io/@hoyo1744/PostgreSQL의-ShareLock-ExclusiveLock))
          - 13초 이상 소요되는 쿼리를 CTE를 활용해 1.3로 성능 개선 ([분석문서](https://velog.io/@hoyo1744/PostgreSQL-%EC%8A%A4%EC%B9%BC%EB%9D%BC-%EC%84%9C%EB%B8%8C-%EC%BF%BC%EB%A6%AC%EB%A5%BC-CTE%EB%A1%9C-%EC%84%B1%EB%8A%A5-%EA%B0%9C%EC%84%A0%ED%95%98%EA%B8%B0))



  - title: Activity
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 백엔드 부트캠프 
        sub_title: Loopers 현직자 백엔드 과정
        description: | # this will include new lines to allow paragraphs
          루프팩 벡엔드 1기 교육 수료

  - title: Skill # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Backend
        description: | # this will include new lines to allow paragraphs
          - Java
          - Spring Boot, Spring Batch
          - JPA, QueryDSL
          - JUnit5, Mockito, RestAssured
          - Gradle, Maven
      - layout: left
        title: DevOps
        description: | # this will include new lines to allow paragraphs
          - PostgreSQL
          - Kafka, Redis
          - MongoDB
          - JMeter
          - Git

  - title: Certificate # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 정보처리기사
        description: | # this will include new lines to allow paragraphs
          - 한국산업인력공단

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
